### PR TITLE
Create autocomplete.cpp

### PR DESCRIPTION
**Pull request by arkogupta**
Added C++ solution to the autocomplete problem

### CODE REVIEW

**Comment by samgh** [comment]
Awesome, thanks for contributing this! Three nitpicky things:
1. Can you lowercase the subdirectory? ("cpp" instead of "Cpp")
2. Can you add indentation for the main method?
3. Can you add comments?

**Comment by arkogupta** [comment]
Hey.
Did the necessary.
See if it is okay now :)

**Comment by samgh** [comment]
At some point I need to put together some style guidelines and whatnot so everything is more consistent, but for now I'm going to go ahead and merge this :)

**Comment by arkogupta** [comment]
Cool ! 😄

**Pull request merged**
